packages:
  - '.'

allowBuilds:
  esbuild: true
  better-sqlite3: true
  "@tailwindcss/oxide": true
  msw: false

minimumReleaseAgeExclude:
  - shadcn@4.15.0

overrides:
  postcss: 8.5.23
  nanoid: '^3.3.17'
