pub mod agents;
pub mod app_runtime;
pub mod bootstrap;
pub mod central_metadata;
pub mod central_store_location;
pub mod central_updates;
pub mod collections;
pub mod deep_link;
pub mod github_import;
pub mod linker;
pub mod local_archive_import;
pub mod local_remote_sync;
pub mod logs;
pub mod marketplace;
pub mod obsidian;
pub mod portable_state;
pub mod projects;
pub mod saved_views;
pub mod scanner;
pub(crate) mod serde_helpers;
pub mod settings;
mod settings_policy;
pub mod skill_update_inventory;
pub mod skills;
pub mod tag_groups;
pub mod targets;
pub mod usage;

pub const APP_USER_AGENT: &str = concat!(env!("CARGO_PKG_NAME"), "/", env!("CARGO_PKG_VERSION"));
