//! Scan directories registry — formerly part of the legacy Discover feature.
//!
//! Only `scan_directories` survives the Phase 4 purge; the old
//! `discovered_skills` table + indices were dropped together with the
//! services/commands modules they fed.

use crate::db::DbPool;

pub(super) async fn init(pool: &DbPool) -> Result<(), String> {
    sqlx::query(
        "CREATE TABLE IF NOT EXISTS scan_directories (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            path       TEXT NOT NULL UNIQUE,
            label      TEXT,
            is_active  BOOLEAN NOT NULL DEFAULT 1,
            is_builtin BOOLEAN NOT NULL DEFAULT 0,
            added_at   TEXT NOT NULL
        )",
    )
    .execute(pool)
    .await
    .map_err(|e| e.to_string())?;

    // Drop residual discovered_skills artifacts from earlier installs. The
    // table content is regenerated by full-disk scans which no longer run.
    sqlx::query("DROP INDEX IF EXISTS idx_discovered_skills_project_path")
        .execute(pool)
        .await
        .map_err(|e| e.to_string())?;
    sqlx::query("DROP INDEX IF EXISTS idx_discovered_skills_platform_id")
        .execute(pool)
        .await
        .map_err(|e| e.to_string())?;
    sqlx::query("DROP TABLE IF EXISTS discovered_skills")
        .execute(pool)
        .await
        .map_err(|e| e.to_string())?;

    Ok(())
}
