// Runtime command registration is declared once here and consumed by both
// Tauri's handler and compile-time parity inventories.

#[macro_export]
#[doc(hidden)]
macro_rules! __skillport_runtime_commands {
    ($callback:ident) => {
        $callback! {
            get_startup_status => commands::startup::get_startup_status,
            retry_startup => commands::startup::retry_startup,
            rebuild_startup_database => commands::startup::rebuild_startup_database,
            exit_startup => commands::startup::exit_startup,
            mark_import_intent_frontend_ready => commands::deep_link::mark_import_intent_frontend_ready,
            get_bootstrap_snapshot => commands::bootstrap::get_bootstrap_snapshot,
            get_skill_counts_summary => commands::bootstrap::get_skill_counts_summary,
            get_dashboard_central_summary => commands::bootstrap::get_dashboard_central_summary,
            get_app_runtime_info => commands::app_runtime::get_app_runtime_info,
            list_targets => commands::targets::list_targets,
            get_target_config_quarantine_status => commands::targets::get_target_config_quarantine_status,
            list_wsl_distributions => commands::targets::list_wsl_distributions,
            create_ssh_target => commands::targets::create_ssh_target,
            update_ssh_target => commands::targets::update_ssh_target,
            test_ssh_target => commands::targets::test_ssh_target,
            update_ssh_target_password => commands::targets::update_ssh_target_password,
            create_wsl_target => commands::targets::create_wsl_target,
            update_wsl_target => commands::targets::update_wsl_target,
            test_wsl_target => commands::targets::test_wsl_target,
            delete_target => commands::targets::delete_target,
            set_active_target => commands::targets::set_active_target,
            get_active_target => commands::targets::get_active_target,
            preview_local_remote_sync => commands::local_remote_sync::preview_local_remote_sync,
            apply_local_remote_sync => commands::local_remote_sync::apply_local_remote_sync,
            list_operation_logs => commands::logs::list_operation_logs,
            get_operation_log => commands::logs::get_operation_log,
            clear_operation_logs => commands::logs::clear_operation_logs,
            export_operation_logs => commands::logs::export_operation_logs,
            list_pending_fs_db_operations => commands::logs::list_pending_fs_db_operations,
            retry_fs_db_operation => commands::logs::retry_fs_db_operation,
            preview_fs_db_operation_reconciliation => commands::logs::preview_fs_db_operation_reconciliation,
            reconcile_fs_db_operation => commands::logs::reconcile_fs_db_operation,
            get_daily_operation_counts => commands::logs::get_daily_operation_counts,
            list_runtime_log_files => commands::logs::list_runtime_log_files,
            read_runtime_log_file => commands::logs::read_runtime_log_file,
            export_runtime_log_file => commands::logs::export_runtime_log_file,
            clear_runtime_logs => commands::logs::clear_runtime_logs,
            record_frontend_runtime_log => commands::logs::record_frontend_runtime_log,
            scan_all_skills => commands::scanner::scan_all_skills,
            get_agents => commands::agents::get_agents,
            detect_agents => commands::agents::detect_agents,
            list_platform_paths => commands::agents::list_platform_paths,
            add_custom_agent => commands::agents::add_custom_agent,
            update_custom_agent => commands::agents::update_custom_agent,
            remove_custom_agent => commands::agents::remove_custom_agent,
            set_agent_enabled => commands::agents::set_agent_enabled,
            install_skill_to_agent => commands::linker::install_skill_to_agent,
            uninstall_skill_from_agent => commands::linker::uninstall_skill_from_agent,
            batch_uninstall_skills_from_agent => commands::linker::batch_uninstall_skills_from_agent,
            batch_install_to_agents => commands::linker::batch_install_to_agents,
            batch_install_central_skills => commands::linker::batch_install_central_skills,
            get_skills_by_agent => commands::skills::get_skills_by_agent,
            get_central_skills => commands::skills::get_central_skills,
            get_central_skills_page => commands::skills::get_central_skills_page,
            preview_delete_central_skills => commands::skills::preview_delete_central_skills,
            delete_central_skill => commands::skills::delete_central_skill,
            delete_central_skills => commands::skills::delete_central_skills,
            preview_reset_unknown_source_skills => commands::skills::preview_reset_unknown_source_skills,
            reset_unknown_source_skills => commands::skills::reset_unknown_source_skills,
            preview_delete_skill_repository => commands::skills::preview_delete_skill_repository,
            delete_skill_repository => commands::skills::delete_skill_repository,
            get_skill_detail => commands::skills::get_skill_detail,
            read_skill_content => commands::skills::read_skill_content,
            read_file_by_path => commands::skills::read_file_by_path,
            list_directory_tree => commands::skills::list_directory_tree,
            open_in_file_manager => commands::skills::open_in_file_manager,
            get_skill_repositories => commands::central_metadata::get_skill_repositories,
            create_or_update_skill_repository => commands::central_metadata::create_or_update_skill_repository,
            assign_skills_to_repository => commands::central_metadata::assign_skills_to_repository,
            set_skill_repository_pinned => commands::central_metadata::set_skill_repository_pinned,
            get_skill_tags => commands::central_metadata::get_skill_tags,
            get_central_top_tags => commands::central_metadata::get_central_top_tags,
            create_skill_tag => commands::central_metadata::create_skill_tag,
            assign_skill_tags => commands::central_metadata::assign_skill_tags,
            unassign_skill_tags => commands::central_metadata::unassign_skill_tags,
            suggest_skill_tags => commands::central_metadata::suggest_skill_tags,
            bulk_suggest_skill_tags => commands::central_metadata::bulk_suggest_skill_tags,
            cancel_ai_tag_job => commands::central_metadata::cancel_ai_tag_job,
            get_pending_ai_tag_reviews => commands::central_metadata::get_pending_ai_tag_reviews,
            accept_ai_tag_review => commands::central_metadata::accept_ai_tag_review,
            skip_ai_tag_review => commands::central_metadata::skip_ai_tag_review,
            preview_central_store_location_change => commands::central_store_location::preview_central_store_location_change,
            apply_central_store_location_change => commands::central_store_location::apply_central_store_location_change,
            get_central_skill_update_states => commands::central_updates::get_central_skill_update_states,
            check_central_skill_updates => commands::central_updates::check_central_skill_updates,
            check_central_repository_sync => commands::central_updates::check_central_repository_sync,
            apply_central_repository_sync => commands::central_updates::apply_central_repository_sync,
            update_central_skills => commands::central_updates::update_central_skills,
            cancel_central_skill_updates => commands::central_updates::cancel_central_skill_updates,
            keep_remote_missing_central_skills => commands::central_updates::keep_remote_missing_central_skills,
            refresh_skill_update_inventory => commands::skill_update_inventory::refresh_skill_update_inventory,
            retry_failed_update_repositories => commands::skill_update_inventory::retry_failed_update_repositories,
            get_skill_update_inventory => commands::skill_update_inventory::get_skill_update_inventory,
            clear_skill_update_inventory => commands::skill_update_inventory::clear_skill_update_inventory,
            apply_skill_update_decisions => commands::skill_update_inventory::apply_skill_update_decisions,
            force_update_central_skills => commands::skill_update_inventory::force_update_central_skills,
            force_mirror_central_repositories => commands::skill_update_inventory::force_mirror_central_repositories,
            scan_platform_duplicate_skills => commands::skill_update_inventory::scan_platform_duplicate_skills,
            scan_deleted_platform_copies => commands::skill_update_inventory::scan_deleted_platform_copies,
            create_collection => commands::collections::create_collection,
            get_collections => commands::collections::get_collections,
            get_collection_detail => commands::collections::get_collection_detail,
            add_skill_to_collection => commands::collections::add_skill_to_collection,
            remove_skill_from_collection => commands::collections::remove_skill_from_collection,
            delete_collection => commands::collections::delete_collection,
            update_collection => commands::collections::update_collection,
            batch_install_collection => commands::collections::batch_install_collection,
            export_collection => commands::collections::export_collection,
            import_collection => commands::collections::import_collection,
            get_scan_directories => commands::settings::get_scan_directories,
            add_scan_directory => commands::settings::add_scan_directory,
            remove_scan_directory => commands::settings::remove_scan_directory,
            set_scan_directory_active => commands::settings::set_scan_directory_active,
            get_setting => commands::settings::get_setting,
            get_settings => commands::settings::get_settings,
            set_setting => commands::settings::set_setting,
            set_settings => commands::settings::set_settings,
            get_ai_api_key_state => commands::settings::get_ai_api_key_state,
            set_ai_api_key => commands::settings::set_ai_api_key,
            clear_ai_api_key => commands::settings::clear_ai_api_key,
            get_github_pat => commands::github_import::get_github_pat,
            set_github_pat => commands::github_import::set_github_pat,
            clear_github_pat => commands::github_import::clear_github_pat,
            test_github_pat => commands::github_import::test_github_pat,
            get_obsidian_vaults => commands::obsidian::get_obsidian_vaults,
            get_obsidian_vault_skills => commands::obsidian::get_obsidian_vault_skills,
            open_obsidian_path => commands::obsidian::open_obsidian_path,
            import_obsidian_skill_to_central => commands::obsidian::import_obsidian_skill_to_central,
            import_obsidian_skill_to_platform => commands::obsidian::import_obsidian_skill_to_platform,
            preview_github_repo_import => commands::github_import::preview_github_repo_import,
            import_github_repo_skills => commands::github_import::import_github_repo_skills,
            fetch_github_skill_markdown => commands::github_import::fetch_github_skill_markdown,
            discard_github_repo_preview_snapshot => commands::github_import::discard_github_repo_preview_snapshot,
            preview_local_skill_archive => commands::local_archive_import::preview_local_skill_archive,
            import_local_skill_archive => commands::local_archive_import::import_local_skill_archive,
            pick_project_folder => commands::projects::pick_project_folder,
            add_project => commands::projects::add_project,
            list_projects => commands::projects::list_projects,
            rename_project => commands::projects::rename_project,
            set_project_pinned => commands::projects::set_project_pinned,
            rescan_project => commands::projects::rescan_project,
            get_project_skills => commands::projects::get_project_skills,
            remove_project => commands::projects::remove_project,
            install_skill_to_project => commands::projects::install_skill_to_project,
            uninstall_skill_from_project => commands::projects::uninstall_skill_from_project,
            list_projects_using_skill => commands::projects::list_projects_using_skill,
            list_registries => commands::marketplace::list_registries,
            add_registry => commands::marketplace::add_registry,
            remove_registry => commands::marketplace::remove_registry,
            sync_registry => commands::marketplace::sync_registry,
            sync_registry_with_options => commands::marketplace::sync_registry_with_options,
            search_marketplace_skills => commands::marketplace::search_marketplace_skills,
            install_marketplace_skill => commands::marketplace::install_marketplace_skill,
            search_skills_sh => commands::marketplace::search_skills_sh,
            resolve_skills_sh_url => commands::marketplace::resolve_skills_sh_url,
            browse_skills_sh_directory => commands::marketplace::browse_skills_sh_directory,
            read_skills_sh_file => commands::marketplace::read_skills_sh_file,
            install_from_skills_sh => commands::marketplace::install_from_skills_sh,
            explain_skill => commands::marketplace::explain_skill,
            test_ai_connection => commands::marketplace::test_ai_connection,
            get_skill_explanation => commands::marketplace::get_skill_explanation,
            get_skill_explanation_summaries => commands::marketplace::get_skill_explanation_summaries,
            explain_skill_stream => commands::marketplace::explain_skill_stream,
            refresh_skill_explanation => commands::marketplace::refresh_skill_explanation,
            export_skillport_state => commands::portable_state::export_skillport_state,
            preview_skillport_state_import => commands::portable_state::preview_skillport_state_import,
            preview_skillport_state_import_file => commands::portable_state::preview_skillport_state_import_file,
            save_skillport_state_export => commands::portable_state::save_skillport_state_export,
            import_skillport_state => commands::portable_state::import_skillport_state,
            cancel_skillport_state_portability => commands::portable_state::cancel_skillport_state_portability,
            list_saved_views => commands::saved_views::list_saved_views,
            create_saved_view => commands::saved_views::create_saved_view,
            update_saved_view => commands::saved_views::update_saved_view,
            delete_saved_view => commands::saved_views::delete_saved_view,
            reorder_saved_views => commands::saved_views::reorder_saved_views,
            list_tag_groups => commands::tag_groups::list_tag_groups,
            create_tag_group => commands::tag_groups::create_tag_group,
            update_tag_group => commands::tag_groups::update_tag_group,
            delete_tag_group => commands::tag_groups::delete_tag_group,
            reorder_tag_groups => commands::tag_groups::reorder_tag_groups,
            set_tag_group => commands::tag_groups::set_tag_group,
            usage_refresh => commands::usage::usage_refresh,
            usage_get_overview => commands::usage::usage_get_overview,
            usage_get_recent => commands::usage::usage_get_recent,
            usage_get_providers => commands::usage::usage_get_providers,
            usage_get_skill_detail => commands::usage::usage_get_skill_detail,
            usage_get_skill_counts => commands::usage::usage_get_skill_counts,
            usage_get_skill_usage_stats => commands::usage::usage_get_skill_usage_stats,
            usage_resolve_skill_id => commands::usage::usage_resolve_skill_id,
            usage_get_scope_info => commands::usage::usage_get_scope_info,
            usage_get_unused_skills => commands::usage::usage_get_unused_skills,
            skills_cli_doctor => commands::skills_cli::skills_cli_doctor,
            skills_cli_list_global => commands::skills_cli::skills_cli_list_global,
            skills_cli_install_targets => commands::skills_cli::skills_cli_install_targets,
            skills_cli_preview_source => commands::skills_cli::skills_cli_preview_source,
            skills_cli_add_global => commands::skills_cli::skills_cli_add_global,
            skills_cli_remove_global => commands::skills_cli::skills_cli_remove_global,
            cancel_skills_cli_job => commands::skills_cli::cancel_skills_cli_job,
        }
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! __skillport_generated_commands {
    ($callback:ident) => {
        $callback! {
            preview_local_remote_sync => commands::local_remote_sync::preview_local_remote_sync,
            apply_local_remote_sync => commands::local_remote_sync::apply_local_remote_sync,
            install_skill_to_agent => commands::linker::install_skill_to_agent,
            batch_install_to_agents => commands::linker::batch_install_to_agents,
            batch_install_central_skills => commands::linker::batch_install_central_skills,
            delete_central_skill => commands::skills::delete_central_skill,
            delete_central_skills => commands::skills::delete_central_skills,
            delete_skill_repository => commands::skills::delete_skill_repository,
            unassign_skill_tags => commands::central_metadata::unassign_skill_tags,
            preview_central_store_location_change => commands::central_store_location::preview_central_store_location_change,
            apply_central_store_location_change => commands::central_store_location::apply_central_store_location_change,
            get_central_skill_update_states => commands::central_updates::get_central_skill_update_states,
            apply_central_repository_sync => commands::central_updates::apply_central_repository_sync,
            keep_remote_missing_central_skills => commands::central_updates::keep_remote_missing_central_skills,
            refresh_skill_update_inventory => commands::skill_update_inventory::refresh_skill_update_inventory,
            retry_failed_update_repositories => commands::skill_update_inventory::retry_failed_update_repositories,
            get_skill_update_inventory => commands::skill_update_inventory::get_skill_update_inventory,
            clear_skill_update_inventory => commands::skill_update_inventory::clear_skill_update_inventory,
            force_update_central_skills => commands::skill_update_inventory::force_update_central_skills,
            force_mirror_central_repositories => commands::skill_update_inventory::force_mirror_central_repositories,
            scan_platform_duplicate_skills => commands::skill_update_inventory::scan_platform_duplicate_skills,
            scan_deleted_platform_copies => commands::skill_update_inventory::scan_deleted_platform_copies,
            remove_skill_from_collection => commands::collections::remove_skill_from_collection,
            delete_collection => commands::collections::delete_collection,
            batch_install_collection => commands::collections::batch_install_collection,
            import_collection => commands::collections::import_collection,
            remove_scan_directory => commands::settings::remove_scan_directory,
            get_ai_api_key_state => commands::settings::get_ai_api_key_state,
            set_ai_api_key => commands::settings::set_ai_api_key,
            clear_ai_api_key => commands::settings::clear_ai_api_key,
            get_github_pat => commands::github_import::get_github_pat,
            set_github_pat => commands::github_import::set_github_pat,
            clear_github_pat => commands::github_import::clear_github_pat,
            test_github_pat => commands::github_import::test_github_pat,
            import_obsidian_skill_to_central => commands::obsidian::import_obsidian_skill_to_central,
            import_obsidian_skill_to_platform => commands::obsidian::import_obsidian_skill_to_platform,
            remove_project => commands::projects::remove_project,
            install_skill_to_project => commands::projects::install_skill_to_project,
            uninstall_skill_from_project => commands::projects::uninstall_skill_from_project,
            remove_registry => commands::marketplace::remove_registry,
            install_marketplace_skill => commands::marketplace::install_marketplace_skill,
            install_from_skills_sh => commands::marketplace::install_from_skills_sh,
            test_ai_connection => commands::marketplace::test_ai_connection,
            skills_cli_doctor => commands::skills_cli::skills_cli_doctor,
            skills_cli_list_global => commands::skills_cli::skills_cli_list_global,
            skills_cli_install_targets => commands::skills_cli::skills_cli_install_targets,
            skills_cli_preview_source => commands::skills_cli::skills_cli_preview_source,
            skills_cli_add_global => commands::skills_cli::skills_cli_add_global,
            skills_cli_remove_global => commands::skills_cli::skills_cli_remove_global,
            cancel_skills_cli_job => commands::skills_cli::cancel_skills_cli_job,
        }
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! __skillport_build_handler {
    ($($name:ident => $command:path,)+) => {
        tauri::generate_handler![$($command),+]
    };
}

#[macro_export]
macro_rules! runtime_command_handler {
    () => {
        $crate::__skillport_runtime_commands!(__skillport_build_handler)
    };
}

macro_rules! build_command_names {
    ($($name:ident => $command:path,)+) => {
        &[$(stringify!($name)),+]
    };
}

pub const RUNTIME_COMMAND_NAMES: &[&str] =
    crate::__skillport_runtime_commands!(build_command_names);
pub const GENERATED_COMMAND_NAMES: &[&str] =
    crate::__skillport_generated_commands!(build_command_names);
